export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const USER_LOGGED = 'USER_LOGGED';
export const IMAGE_UPDATED = 'IMAGE_UPDATED';
export const FEED_SETTINGS_UPDATED = 'FEED_SETTINGS_UPDATED';