//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatHistory
    {
        public int messageId { get; set; }
        public Nullable<int> datetime { get; set; }
        public string text { get; set; }
        public Nullable<int> fromMemberId { get; set; }
        public Nullable<int> toMemberId { get; set; }
        public Nullable<int> chatRoomId { get; set; }
        public Nullable<bool> markAsRead { get; set; }
        public Nullable<bool> meetingMsg { get; set; }
        public string meetingDateLabel { get; set; }
        public string meetingEventTitle { get; set; }
        public string meetingTimeLabel { get; set; }
        public Nullable<int> meetingUnixDate { get; set; }
        public string meetingLocationLabel { get; set; }
    }
}
