//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedSetting
    {
        public int id { get; set; }
        public Nullable<int> memberId { get; set; }
        public string memberType { get; set; }
        public string postLocation { get; set; }
        public string participantGender { get; set; }
        public string participantAgeRange { get; set; }
    }
}
