//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interaction
    {
        public int id { get; set; }
        public Nullable<int> memberId { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> postId { get; set; }
        public Nullable<int> otherMemberId { get; set; }
        public string interactionType { get; set; }
        public Nullable<int> strength { get; set; }
        public Nullable<int> unixdate { get; set; }
        public string categoryName { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Member Member { get; set; }
        public virtual Post Post { get; set; }
    }
}
