//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int id { get; set; }
        public Nullable<int> invitingMemberId { get; set; }
        public string invitationText { get; set; }
        public Nullable<int> acceptingMemberId { get; set; }
        public Nullable<int> datetime { get; set; }
        public Nullable<int> locationId { get; set; }
        public Nullable<bool> didAccept { get; set; }
        public Nullable<bool> didHappen { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
